// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOCEwIN4DRA-DMpwRhZ0rl7wyEPGz01Wk',
    appId: '1:759081073032:web:fc82129a47ca1a9a40623d',
    messagingSenderId: '759081073032',
    projectId: 'smart-app-2da01',
    authDomain: 'smart-app-2da01.firebaseapp.com',
    storageBucket: 'smart-app-2da01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWHGnNch0AWhvLrI3hq_Z8f0-JL-vBwnI',
    appId: '1:759081073032:android:6603e9c691d4e7d440623d',
    messagingSenderId: '759081073032',
    projectId: 'smart-app-2da01',
    storageBucket: 'smart-app-2da01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOvz_QprviTmCBnK7rwTOyQInLK-yKp9Y',
    appId: '1:759081073032:ios:f3909edb7a2e4f3240623d',
    messagingSenderId: '759081073032',
    projectId: 'smart-app-2da01',
    storageBucket: 'smart-app-2da01.firebasestorage.app',
    iosBundleId: 'com.elamri.elamriApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOvz_QprviTmCBnK7rwTOyQInLK-yKp9Y',
    appId: '1:759081073032:ios:f3909edb7a2e4f3240623d',
    messagingSenderId: '759081073032',
    projectId: 'smart-app-2da01',
    storageBucket: 'smart-app-2da01.firebasestorage.app',
    iosBundleId: 'com.elamri.elamriApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOCEwIN4DRA-DMpwRhZ0rl7wyEPGz01Wk',
    appId: '1:759081073032:web:feef33afeecd020640623d',
    messagingSenderId: '759081073032',
    projectId: 'smart-app-2da01',
    authDomain: 'smart-app-2da01.firebaseapp.com',
    storageBucket: 'smart-app-2da01.firebasestorage.app',
  );
}
